### ISSUE TITLE
Ragdoll corpses(Crash while exiting world)

### ISSUE THREAD

**Issue by quentin452** [quentin452/The-Lord-of-the-Rings#24]
```
[18:16:22] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ClientTickEvent@274209e7:
java.lang.NullPointerException
	at net.gobbob.RagdollCorpses.physics.RagdollCorpse.getDistanceToPlayer(RagdollCorpse.java:127) ~[RagdollCorpse.class:?]
	at net.gobbob.RagdollCorpses.event.EventHandler_Ragdoll.onClientTick(EventHandler_Ragdoll.java:54) ~[EventHandler_Ragdoll.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_425_EventHandler_Ragdoll_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:7006) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
[18:16:22] [Client thread/ERROR] [FML]: Index: 7 Listeners:
[18:16:22] [Client thread/ERROR] [FML]: 0: NORMAL
[18:16:22] [Client thread/ERROR] [FML]: 1: ASM: lotr.client.render.entity.LOTRSwingHandler@51361fce onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 2: ASM: lotr.client.LOTRTickHandlerClient@5f610784 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 3: ASM: xonin.backhand.client.ClientTickHandler@20024d64 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 4: ASM: ichun.client.core.TickHandlerClient@7d84e160 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 5: ASM: ichun.client.voxel.TrailTicker@7896c44d worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 6: ASM: INSTANCE tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 7: ASM: net.gobbob.RagdollCorpses.event.EventHandler_Ragdoll@38fcde16 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 8: ASM: codechicken.core.internal.CCCEventHandler@496a8896 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 9: ASM: codechicken.nei.ClientHandler@7721c972 tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 10: ASM: INSTANCE onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 11: ASM: com.gildedgames.the_aether.client.audio.AetherMusicHandler@38667731 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 12: ASM: com.gildedgames.the_aether.client.AetherClientEvents@3cd50083 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 13: ASM: hunternif.mc.atlas.ClientProxy@5e7c69a2 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 14: ASM: vazkii.botania.common.core.handler.CommonTickHandler@2bb2b8a8 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 15: ASM: vazkii.botania.client.core.handler.ClientTickHandler@7018c5c4 clientTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 16: ASM: vazkii.botania.client.core.handler.CorporeaAutoCompleteHandler@4279fdfe onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 17: ASM: makamys.coretweaks.CoreTweaksMod@559ce43f onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 18: ASM: ganymedes01.etfuturum.core.handlers.ClientEventHandler@73ef75d2 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 19: ASM: ganymedes01.etfuturum.spectator.SpectatorModeClient@2feb3ee4 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 20: ASM: bre.fpsreducer.WakeupEventHandler@59cfa0ae onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 21: ASM: mcp.mobius.waila.overlay.WailaTickHandler@5ee0df1f tickClient(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 22: ASM: cofh.core.render.ShaderHelper@6366861b clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 23: ASM: net.tclproject.entityculling.EntityCulling@49de2e63 doClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 24: ASM: com.mitchej123.hodgepodge.client.ClientTicker@928b409 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 25: ASM: vazkii.botania.common.block.BlockPistonRelay@9d4a77 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 26: ASM: me.lucko.spark.forge.Forge1710TickHook@1e2904f2 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[18:16:22] [Client thread/ERROR] [FML]: 27: ASM: me.lucko.spark.forge.Forge1710TickReporter@1ceeb6a6 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[18:16:22] [Client thread/ERROR] [coretweaks]: #@!@# Game crashed! CoreTweaks will attempt to keep the game running.
[18:16:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[18:16:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.gobbob.RagdollCorpses.physics.RagdollCorpse.getDistanceToPlayer(RagdollCorpse.java:127)

**Comment by quentin452** [comment]
Fixed on OptimizationsAndTweaks side indev
