### ISSUE TITLE
[compatibility] NEI Recipe Handlers

### ISSUE THREAD

**Issue by Mcayear** [quentin452/The-Lord-of-the-Rings#29]
Working with [neiRecipeHandlers v1.1.0-BETA.jar](https://pan.9991565.xyz/AliyunDrive/mods/neiRecipeHandlers-1.1.0-BETA.jar) will cause a crash.

from: https://github.com/CraftedMods/nei-recipe-handlers

## LOTR version
[LOTRModfork.v36.29.jar](https://github.com/quentin452/The-Lord-of-the-Rings/releases/download/v36.29/LOTRModfork.v36.29.jar)

## Client logs

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 24-12-17 下午1:19
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: coinCount_excludedGUIs
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:2993)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:112)
	at oolloo.jlw.Wrapper.main(Wrapper.java:105)
Caused by: java.lang.NoSuchFieldError: coinCount_excludedGUIs
	at craftedMods.lotr.recipes.internal.IntegratedRecipeHandlerFactory.disableCoinCountDisplayForGUIs(IntegratedRecipeHandlerFactory.java:577)
	at craftedMods.lotr.recipes.internal.IntegratedRecipeHandlerFactory.<clinit>(IntegratedRecipeHandlerFactory.java:549)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at craftedMods.recipes.utils.NEIRecipeHandlersUtils.lambda$discoverRegisteredHandlers$0(NEIRecipeHandlersUtils.java:241)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at craftedMods.recipes.utils.NEIRecipeHandlersUtils.discoverRegisteredHandlers(NEIRecipeHandlersUtils.java:234)
	at craftedMods.recipes.provider.RecipeHandlerManager.discoverRecipeHandlersInClasspath(RecipeHandlerManager.java:86)
	at craftedMods.recipes.provider.RecipeHandlerManager.init(RecipeHandlerManager.java:64)
	at craftedMods.recipes.provider.NEIIntegrationManager.init(NEIIntegrationManager.java:118)
	at craftedMods.recipes.NEIRecipeHandlers.onPostInit(NEIRecipeHandlers.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 493303280 bytes (470 MB) / 1094713344 bytes (1044 MB) up to 3865051136 bytes (3686 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn552m -Xmx3686m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E3 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJ	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJ	CodeChickenCore{1.1.6} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJ	NotEnoughItems{2.3.18-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.3.18-GTNH.jar) 
	UCHIJ	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJ	uuidoffline{1.0} [UUIDOffline] ([GUI修复]uuidoffline-1.0.jar) 
	UCHIJ	XaeroMinimap{21.10.27} [Xaero's Minimap] ([旅行地图2]Xaeros_Minimap_21.10.27_Forge_1.7.10.jar) 
	UCHIJ	XaeroWorldMap{1.14.1.20} [Xaero's World Map] ([旅行地图2]XaerosWorldMap_1.14.1.20_Forge_1.7.10.jar) 
	UCHIJ	coretweaks{0.3.3.2} [CoreTweaks] ([核显修复]CoreTweaks-1.7.10-0.3.3.2+nomixin.jar) 
	UCHIJ	neodymium{0.2.5} [Neodymium] ([核显修复]neodymium-1.7.10-0.2.5+nomixin.jar) 
	UCHIJ	unimixins{0.1.19} [UniMixins] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	unimixins-mixin{0.1.19} [UniMixins: Mixin (UniMix)] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	unimixins-compat{0.1.19} [UniMixins: Compatibility] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	mixingasm{0.3} [UniMixins: Mixingasm] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	spongemixins{2.0.1} [UniMixins: SpongeMixins] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	gasstation{0.5.1} [UniMixins: GasStation] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	mixinextras{0.1.19} [UniMixins: MixinExtras] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJ	AppleCore{3.0.0} [AppleCore] (AppleCore-mc1.7.10-3.0.0.jar) 
	UCHIJ	hud{1.1a} [Better HUD] (Better HUD-V1.1.zip) 
	UCHIJ	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCHIJ	lotr{Update v36.15 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRModfork.v36.29.jar) 
	UCHIJ	neiutilities{0.1.8} [NEI Utilities] (NEI-Utilities-1.7.10-0.1.8.jar) 
	UCHIE	neirecipehandlers{1.1.0-BETA} [NEI Recipe Handlers] (neiRecipeHandlers-1.1.0-BETA.jar) 
	UCHIJ	nechar{1.4.6} [Not Enough Characters] (NotEnoughCharacters-1.7.10-1.4.8.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 31.0.101.2111' Renderer: 'Intel(R) UHD Graphics 620'
	Mixins in Stacktrace: 
		net.minecraft.client.Minecraft:
			coretweaks.mixin.json:tweak.crashhandler.MixinMinecraft from mod coretweaks
		cpw.mods.fml.common.LoadController:
			mixins.gtnhmixins.json:LateMixinOrchestrationMixin from mod (unknown)
			mixin.mixinbooterlegacy.json:LoadControllerMixin from mod (unknown)
	OptiFine Version: OptiFine_1.7.10_HD_U_E3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 31.0.101.2111
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8
```

**Comment by Mcayear** [comment]
There are also compatibility issues with [DVS v1.0.7](https://legacy.curseforge.com/minecraft/mc-mods/dvs) plugins
