### ISSUE TITLE
[FATAL] `net.minecraft.network.NetHandlerPlayServer` Method `playerEntity` Invalid

### ISSUE THREAD

**Issue by Mcayear** [quentin452/The-Lord-of-the-Rings#31]
## Issue Summary
While playing in Middle-earth, I attempted to use the fast travel feature by opening the map and selecting a waypoint. However, an unexpected issue occurred where the teleportation was interrupted immediately, even though I did not move.

## Detailed Explanation
To diagnose the problem, I introduced a `RuntimeException` to capture the error stack trace, which led me to pinpoint the issue within the `LOTRNetHandlerPlayServer#processPlayer` method.

**RuntimeException**
```
java.lang.RuntimeException: lotr.fastTravel.motion
	at lotr.common.LOTRPlayerData.cancelFastTravel(LOTRPlayerData.java:526)
	at lotr.common.LOTRNetHandlerPlayServer.func_147347_a(LOTRNetHandlerPlayServer.java:140)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Upon further investigation, I discovered that the `playerEntity#posX` method consistently returns an incorrect value of `0.0`. The `playerEntity` is part of the `net.minecraft.network.NetHandlerPlayServer` class. 

This incorrect value causes multiple logic errors within the mod, such as:
- `LOTRAttackTiming.fullAttackTime` 
- `LOTRAttackTiming.prevAttackTime` 

Both of these fields in the `LOTR Attack Indicator` are perpetually set to `0`, disrupting the intended functionality.

## Steps to Reproduce
1. Launch Minecraft with the LOTR mod installed.
2. Enter the Middle-earth region.
3. Open the in-game map.
4. Click on a waypoint to initiate fast travel.
5. Observe that the teleportation is interrupted despite no movement.

## Expected Behavior
Selecting a waypoint on the map should initiate a smooth and uninterrupted fast travel sequence, transporting the player to the chosen location.

## Actual Behavior
Teleportation is immediately interrupted, and the player remains in the original location without any movement.

## Environment
- **Minecraft Version:** 1.7.10
- **Forge Version:** 
- **LOTR Mod Version:** [1.7.10 v36.29](https://github.com/quentin452/The-Lord-of-the-Rings/releases/tag/v36.29)
- **Other Installed Mods:** [List any other mods you have installed that might be relevant]
<details> <summary>Detailed</summary>
<pre>
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E3 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAA	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.1.6} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.10-v6} [InputFix] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.3.18-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.3.18-GTNH.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	uuidoffline{1.0} [UUIDOffline] ([GUI修复]uuidoffline-1.0.jar) 
	UCHIJAAAA	XaeroMinimap{21.10.27} [Xaero's Minimap] ([旅行地图2]Xaeros_Minimap_21.10.27_Forge_1.7.10.jar) 
	UCHIJAAAA	XaeroWorldMap{1.14.1.20} [Xaero's World Map] ([旅行地图2]XaerosWorldMap_1.14.1.20_Forge_1.7.10.jar) 
	UCHIJAAAA	coretweaks{0.3.3.2} [CoreTweaks] ([核显修复]CoreTweaks-1.7.10-0.3.3.2+nomixin.jar) 
	UCHIJAAAA	neodymium{0.2.5} [Neodymium] ([核显修复]neodymium-1.7.10-0.2.5+nomixin.jar) 
	UCHIJAAAA	unimixins{0.1.19} [UniMixins] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	unimixins-mixin{0.1.19} [UniMixins: Mixin (UniMix)] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	unimixins-compat{0.1.19} [UniMixins: Compatibility] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	mixingasm{0.3} [UniMixins: Mixingasm] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	gasstation{0.5.1} [UniMixins: GasStation] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	mixinextras{0.1.19} [UniMixins: MixinExtras] ([核显修复前置]+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	AppleCore{3.0.0} [AppleCore] (AppleCore-mc1.7.10-3.0.0.jar) 
	UCHIJAAAA	lotr{Update v36.15 for Minecraft 1.7.10} [The Lord of the Rings Mod] (lotr-v36.29-giteeMain.5+89d44b2fe9-dirty.jar) 
	UCHIJAAAA	dvs{1.0.7} [Structure Scanner] (DVS-1.0.7.jar) 
	UCHIJAAAA	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCHIJAAAA	attackindicator{1.6.4} [LOTR Attack Indicator] (LOTR Attack Indicator-1.6.4.jar) 
</pre>
</details>

## Additional Information
- A `RuntimeException` was thrown to capture the error stack, which helped in identifying the problematic method.
- The issue seems to stem from the `playerEntity#posX` method always returning `0.0`, causing downstream logic errors in the mod's attack timing mechanisms.

## Request for Assistance
Due to the critical nature of this issue, I am unable to delve deeper into debugging. I kindly request assistance and support to resolve this problem.

## Screenshots/Logs
```java lotr.common.LOTRNetHandlerPlayServer
	@Override
	public void processPlayer(C03PacketPlayer packet) {
		super.processPlayer(packet);
		if (!playerEntity.isRiding() && packet.func_149466_j()) {
			double newX = packet.func_149464_c();
			double newY = packet.func_149467_d();
			double newZ = packet.func_149472_e();
			if (newX != lastX || newY != lastY || newZ != lastZ) {
				LOTRLevelData.getData(playerEntity).cancelFastTravel();
			}
		}
        	lastX = playerEntity.posX;
		lastY = playerEntity.posY;
		lastZ = playerEntity.posZ;
	}
```
![e06f58aeb06c45eb1f678be2cb72324b](https://github.com/user-attachments/assets/7bfc826b-b9d5-40d7-b0c5-d48159ab8787)

---

## Suggested Actions:
1. **Verify Mod and Forge Versions:**
   - Ensure that the versions of Minecraft, Forge, and the LOTR mod are all compatible with each other.
   
2. **Check for Mod Conflicts:**
   - Disable other mods to see if the issue persists, which can help identify if there are any conflicts.
   
3. **Review Recent Changes:**
   - If the issue started occurring after a recent update or change, consider reverting to a previous stable state.
   
4. **Provide Environment Details:**
   - Including specific versions and a list of other installed mods can help maintainers reproduce and address the issue more effectively.

---

**Thank you for your attention to this matter. I look forward to your guidance and support in resolving this issue.**

**Comment by Mcayear** [comment]
The LOTRNetHandlerPlayServer class has a different hash every time, which means that all non-static variables can't hold any values.

![image](https://github.com/user-attachments/assets/55362300-8257-4422-bd6e-d945d7f4bbfc)
![3295d9a0a4a752d6995816c7bb370c92](https://github.com/user-attachments/assets/1dda2148-b4e9-4957-b64c-4a41f031373a)

**Comment by Mcayear** [comment]
resovle at: https://gitee.com/ayear/The-Lord-of-the-Rings/commit/d69671daa9b5d17ce296fd0576db2f6dc34c2656
